#!name=REJECT SR Lite CN Stable

#!desc=iPhone Shadowrocket 精简稳定版（核心屏蔽）

[Rule]
# 拦截这两个数据追踪与广告域名（推荐）
DOMAIN-SUFFIX, app-analytics-services.com, REJECT
DOMAIN-SUFFIX, doubleclick.net, REJECT
DOMAIN-SUFFIX,umeng.com,Reject
DOMAIN-SUFFIX,umengcloud.com,Reject
DOMAIN-SUFFIX, ut.taobao.com,Reject
